version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing Maven"
      - yum install -y maven
  build:
    commands:
      - ./mvnw clean package -DskipTests -Pprod
artifacts:
  files:
    - target/backend-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/**